name: Build MacOS App

on: 
  workflow_dispatch: # Permet de lancer la compilation manuellement

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter reportlab pyinstaller

      - name: Build with PyInstaller
        run: |
          # Commande spécifique pour inclure CustomTkinter sur Mac
          python -m PyInstaller --noconfirm --onedir --windowed \
          --add-data "$(python -c 'import customtkinter; print(customtkinter.__path__[0])'):customtkinter/" \
          app_with_pdf.py

      - name: Package as ZIP
        run: |
          cd dist
          zip -r ../Classly_MacOS.zip app_with_pdf.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Classly-Mac-App
          path: Classly_MacOS.zip
